### ISSUE TITLE
How to close ndndpdk-godemo put autonomously

### ISSUE THREAD

**Issue by aonrdbit** [usnistgov/ndn-dpdk#32]
Hello, this is not a bug, but a question I want to ask.

I am using ubuntu 20.04 on a physical machine, hugepages and driver have been configured, and it has been started successfully.

If I put a segment on node 1 using ndndpdk-gedemo, then I can get it on node 2 using ndndpdk-gedemo. After obtaining, the get process of node 2 ends, but the put process of node 1 will wait forever. Is there any elegant way to automatically end the put process when a segment is acquired once?

Sincerely look forward to your answer, thank you.

**Comment by yoursunny** [comment]
To stop `ndndpdk-godemo put` command, press CTRL+C key, or send a SIGINT signal programmatically.

Stopping a producer when every segment has been retrieved once is an antipattern, because:

* There's no guarantee that every Interest for the served object would reach this producer: the network might have cached some packets so that these Interests will never arrive; the network might have multiple producers, each receiving a subset of Interests.
* It's unsafe to stop the producer when every segment has been retrieved once: some of the segments may have been lost in the network, the consumer or strategy would retransmit the Interest, and the producer shall keep running to satisfy retransmitted Interests.

While it is possible to implement such behavior using NDNgo library, the demo programs should not show such antipattern.
