### ISSUE TITLE
ndn-dpdk import paths ignore Go import path conventions

### ISSUE THREAD

**Issue by kortschak** [usnistgov/ndn-dpdk#4]
The import paths used by ndn-dpdk do not use fully qualified domain names as the first element of import paths. This flies in the face of the Go convention for this (that only stdlib should do this).

**Comment by yoursunny** [comment]
This was intentional: NDN-DPDK has a custom build process for C code, and does not support `go get` installation method.
The reason of having a custom build process is that, C code has dependency to each other across different directories, and they often need to call each other without going through Go, for performance reasons. Thus, I'm building C code as static libraries, then dynamically generate `#cgo` lines to link these static libraries into Go packages that need them.

**Comment by kortschak** [comment]
It breaks [assumptions built into modules](https://godoc.org/golang.org/x/mod/module#CheckPath) and has a good chance of breaking code introspection tools. So long as you're aware of that and are happy to carry the problems, I guess that's your choice.
