### ISSUE TITLE
Generate traffic instead of doing it manually

### ISSUE THREAD

**Issue by rohansuri1996** [usnistgov/ndn-dpdk#47]
Hi again,

Since I am developing a load balancer on ndn dpdk, I would like to generate traffic from one host to another without doing it manually.
We are starting with a simple approach of round robin for transfer from one host to another if it has more than one path.
Currently to check connections I am manually typing  `P ndndpdk-godemo pingclient --name /Q` to check the connection but I would like to generate traffic and monitor which path it takes.

New ideas would be welcomed too.

**Comment by yoursunny** [comment]
You can always start the consumer (and keep it running) via scripts instead of CLI.

Current NDN protocol does not offer a method to find out the path taken by a specific packet.
You can retrieve face counters (from GraphQL) periodically to gain insights on how many packets were transmitted over each link.

**Comment by rohansuri1996** [comment]
> You can always start the consumer (and keep it running) via scripts instead of CLI.
> 
> Current NDN protocol does not offer a method to find out the path taken by a specific packet. You can retrieve face counters (from GraphQL) periodically to gain insights on how many packets were transmitted over each link.

https://github.com/usnistgov/ndntrace Does this tool be able to do the job of finding the route?

**Comment by yoursunny** [comment]
Yes, NDN-Trace can find the route taken by the request packet.
However, it is not compatible with NDN-DPDK.

**Comment by rohansuri1996** [comment]
> Yes, NDN-Trace can find the path taken by the request packet. However, it is not compatible with NDN-DPDK.

Thanks a lot for a quick reply if you don't mind I have a follow-up question. I don't know who to ask these questions but I hope it helps the developer community.

Can faceCounters identify the packets? If you have more than one flow the will I be able to somehow identify the flow? When I am running my script, I see rxData counter increasing which probably denotes the number of packets flowing.

**Comment by yoursunny** [comment]
> Can faceCounters identify the packets? If you have more than one flow the will I be able to somehow identify the flow? When I am running my script, I see rxData counter increasing which probably denotes the number of packets flowing.

Face-level counters cannot identify packet name prefixes.

`rxData` counter indicates how many Data packets arrived at a face since the face was created.
If you retrieve this counter once a second, the difference between two readings indicates how many Data packets arrived at the face in one second.
Such Data packets could be returned to downstream, or could be dropped if it does not match any PIT entry.
