### ISSUE TITLE
Replace custom hrlog with DPDK's trace library

### ISSUE THREAD

**Issue by Pesa** [usnistgov/ndn-dpdk#5]
https://doc.dpdk.org/guides/prog_guide/trace_lib.html

**Comment by yoursunny** [comment]
I have read about **Trace Library** and I believe it is not a suitable replacement for **hrlog** package.

**hrlog** supports on-demand collection of packet processing records.
Upon invoking the `Start()` function, a blank file is generated and packet processing records are written to this file, until `Stop()` is invoked or the requested number of records have been reached.
Packet processing latency collection in NDN-DPDK benchmarks is implemented with **hrlog**.

**Trace Library** allows specifying a trace buffer size (via `--trace-bufsz` EAL parameter) and offers a `rte_trace_save()` function to write the trace buffer to a file.
It has several limitations that make it difficult to satisfy the benchmark use case:

* Trace records are always being collected. The benchmark script cannot ensure records written in a trace file belong to the current run, instead of some earlier run.
* The entirety of the trace buffer must reside in memory, which means large trace buffers (more than a few gigabytes) are infeasible,
* There's no API to retrieve trace filename, other than searching the output directory.

A benefit of **Trace Library** is that it supports lockless trace-emit function.
**hrlog** internally uses `rte_ring` that is also a lockless implementation.

**Comment by Pesa** [comment]
The main goal of this task was actually to switch to the [**CTF**](https://diamon.org/ctf/) format for tracing. I thought using DPDK's trace library was the simplest way to achieve that, but maybe it isn't. I still think switching to CTF is very important for the future as it allows us to use a number of advanced tools to handle CTF traces that already exist and are actively developed. Today, CTF is essentially the _de facto_ standard for low-level tracing. Consider also that so far we've only used this facility for latency measurements, but we're going to have to expand its usage to more things if we want to do more perf analysis and optimization work on the code. And I vastly prefer using something standard rather than reinventing the wheel.

On the technical side, it sounds like we could contribute some improvements to DPDK's trace lib? or can we keep the existing collection infrastructure of hrlog and use DPDK only for the CTF record serialization? if neither are feasible, there are other projects such as [barectf](https://barectf.org/) which might be worth looking into.
